sub_process_types:
  外圆:
    required_params:
      - Cn      #圆圈数量
      - L       # 长度
      - Tr      #过渡半径
      - Cr      #退回半径
      - F       #进给速度
  外圆弧:
    required_params:
      - Cn    #圆圈数量
      - L     # 长度
      - Tr    #过渡半径
      - A     #角度（用于计算切割半径）
      - F     #进给速度
      - xDir  #X 轴方向
      - zDir  #Z 轴方向
      - G71G73  #G71 或 G73 切换模式
  外锥面:
    required_params:
      - R     #半径
      - Tr    #过渡半径
      - Cn    #圆圈数量
      - F     #进给速度
      - G2G3  # 1表示G2（顺时针圆弧），3表示G3（逆时针圆弧）
      - PHi1  #第一个角度增量
      - L     # 长度
  端面:
    required_params:
      - Cn       # 进刀次数
      - Lr       # 退刀量
      - deltaT   # 进刀量
      - CT       # 最后一次进刀的退刀量
      - F        # 进给速度

  切槽:
    required_params:
      - W        # 加工宽度
      - Tw       # 刀具宽度
      - Cn       # 进刀次数
      - Lr       # 退刀量
      - Tr       # 进刀深度
      - F        # 进给速度

  内端面:
    required_params:
      - Cn       # 进刀次数
      - Lr       # 退刀量
      - deltaT   # 进刀量
      - CT       # 最后一次进刀的退刀量
      - F        # 进给速度
  中心孔:
    required_params:
      - Cn      #进刀次数
      - L       #加工长度
      - Tr      #进刀深度
      - Cr      #最后一次进刀的退刀量
      - F       #进给速度
  内锥面:
    required_params:
      - Cn      #进刀次数
      - L       #加工长度
      - Tr      #进刀深度
      - F       #进给速度
      - A       #锥度角度
      - xDir     #X 轴方向
      - zDir    #Z 轴方向
      - G71G73  #加工模式
  内槽:
    required_params:
      - W   #开口宽度
      - Tw  #切槽刀具宽度
      - Cn    #切槽次数
      - Lr    #切槽深度
      - Tr    #进刀深度
      - F   #进给速度
  内弧:
    required_params:
      - R     #半径
      - Tr    #每次进刀量
      - Cn    #进刀次数
      - F     #进给速度
      - G2G3    #切割方式，0表示顺时针(G02)，1表示逆时针(G03)。
      - PHi1    #X轴的增量位置
      - L     # Z轴的增量位置
  内圆:
    required_params:
      - Cn    #进刀次数
      - deltaT    #每次进刀的增量
      - F   #进给速度
      - BT    #退刀时的增量
      - L     #最终的退刀位置
  外反锥面:
    required_params:
      - Tr      #刀具半径或偏移量。
      - F       #进给速率。
      - L       #切割长度。
      - Cn      #切割次数（即工序的循环次数）。
      - A       #锥形面的角度，单位为度。
      - xDir    #X轴的方向 (-1 表示负向，1 表示正向)。
      - zDir    #Z轴的方向 (-1 表示负向，1 表示正向)。
      - G71G73  #Code模式，'G73' 表示深孔钻削，'G71' 表示粗加工模式。
  内反锥面:
    required_params:
      - Tr      #刀具半径或偏移量。
      - F       #进给速率。
      - L       #切割长度。
      - Cn      #切割次数（即工序的循环次数）。
      - A       #锥形面的角度，单位为度。
      - Cr      # 锥形面的半径。
      - xDir    #X轴的方向 (-1 表示负向，1 表示正向)。
      - zDir    #Z轴的方向 (-1 表示负向，1 表示正向)。
      - G71G73  #Code模式，'G73' 表示深孔钻削，'G71' 表示粗加工模式。
  外正锥面:
    required_params:
      - Tr      #刀具半径或偏移量。
      - F       #进给速率。
      - L       #切割长度。
      - Cn      #切割次数（即工序的循环次数）。
      - A       #锥形面的角度，单位为度。
      - Cr      # 锥形面的半径。
      - Cr1     # 锥形面的另一个半径
      - xDir    #X轴的方向 (-1 表示负向，1 表示正向)。
      - zDir    #Z轴的方向 (-1 表示负向，1 表示正向)。
      - G71G73  #Code模式，'G73' 表示深孔钻削，'G71' 表示粗加工模式。
  内正锥面:
    required_params:
      - Tr      #刀具半径或偏移量。
      - F       #进给速率。
      - L       #切割长度。
      - Cn      #切割次数（即工序的循环次数）。
      - A       #锥形面的角度，单位为度。
      - xDir    #X轴的方向 (-1 表示负向，1 表示正向)。
      - zDir    #Z轴的方向 (-1 表示负向，1 表示正向)。
  外直螺纹:
    required_params:
      - L                       # 螺纹加工的长度。
      - Tr                      # 进刀量。
      - Tp                      # 螺距。
      - Cn                      # 螺纹加工的切削次数。
      - Cr                      # 螺纹的根部直径。
      - multi_head              # 多头加工数量。
      - tailLength              # 退尾长度，单位是螺距个数。
      - cuttingDepthSelection   # 切削深度选择，用于决定等距或递减进刀。
  外锥（管）螺纹:
    required_params:
      - L                       # 螺纹加工的长度。
      - Tr                      # 进刀量。
      - Tp                      # 螺距。
      - Cn                      # 螺纹加工的切削次数。
      - A                       # 螺纹的角度（以度为单位）。
      - tailLength              # 退尾长度，单位是螺距个数。
      - startA                  #起始角度。
  内直螺纹:
    required_params:
      - L                       # 螺纹加工的长度。
      - Tr                      # 进刀量。
      - Tp                      # 螺距。
      - Cn                      # 螺纹加工的切削次数。
      - tailLength              # 退尾长度，单位是螺距个数。
      - startA                  #起始角度。
  内锥（管）螺纹:
    required_params:
      - L                       # 螺纹加工的长度。
      - Tr                      # 进刀量。
      - Tp                      # 螺距。
      - Cn                      # 螺纹加工的切削次数。
      - startA                  #起始角度。
      - A                       # 螺纹的角度（以度为单位）。
      - tailLength              # 退尾长度，单位是螺距个数。
  外圆角倒角:
    required_params:
      - R                     # 弧半径。
      - Tr                    # 每次进刀量。
      - Cn                    # 进刀次数。
      - F                     # 进给速度。
      - G2G3                  # 切圆弧方向（0 表示 G02，1 表示 G03）。
      - PHi1                  # 终点的X轴增量位置（用于G73模式）。
      - L                     # 终点的Z轴增量位置。
      - G71G73                # 加工模式（G71 或 G73）。
  外倒角:
    required_params:
      - Cn                    # 进刀次数。
      - Tr                    # 每次进刀量。
      - F                     # 进给速度。
      - L                     # 长度。
      - A                     # 倒角角度。
      - xDir                  # X轴方向。
      - zDir                  # Z轴方向。
      - G71G73                # 加工模式（G71 或 G73）。
  内圆角倒角:
    required_params:
      - R                     # 弧半径。
      - Tr                    # 每次进刀量。
      - Cn                    # 进刀次数。
      - F                     # 进给速度。
      - G2G3                  # 切圆弧方向（0 表示 G02，1 表示 G03）。
      - PHi1                  # 终点的X轴增量位置（用于G73模式）。
      - L                     # 终点的Z轴增量位置。
      - G71G73                # 加工模式（G71 或 G73）。
  内倒角:
    required_params:
      - Cn                    # 进刀次数。
      - Tr                    # 每次进刀量。
      - L                     # 长度。
      - F                     # 进给速度。
      - A                     # 倒角角度。
      - xDir                  # X轴方向。
      - zDir                  # Z轴方向。
      - G71G73                # 加工模式（G71 或 G73）。